# Generated by Django 2.2.3 on 2019-07-09 11:13

import book_generator.enums.book_jobs
import book_generator.enums.chapter_jobs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('rounds', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookPartaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('job', models.CharField(choices=[(book_generator.enums.book_jobs.BookJobs('Writer'), 'Writer'), (book_generator.enums.book_jobs.BookJobs('Illustrator'), 'Illustrator'), (book_generator.enums.book_jobs.BookJobs('Director'), 'Director')], max_length=15)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_generator.Book')),
            ],
            options={
                'db_table': 'book_partaker',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_generator.Book')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='ChapterPartaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('job', models.CharField(choices=[(book_generator.enums.chapter_jobs.ChapterJobs('Writer'), 'Writer'), (book_generator.enums.chapter_jobs.ChapterJobs('Illustrator'), 'Illustrator')], max_length=15)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_generator.Chapter')),
            ],
            options={
                'db_table': 'chapter_partaker',
            },
        ),
        migrations.CreateModel(
            name='BookRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_generator.BookPartaker')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_generator.Book')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_generator.Rule')),
            ],
            options={
                'db_table': 'book_rule',
            },
        ),
        migrations.AddConstraint(
            model_name='chapterpartaker',
            constraint=models.UniqueConstraint(fields=('chapter', 'user', 'job'), name='unique_chapter_partaker_job'),
        ),
        migrations.AddConstraint(
            model_name='bookrule',
            constraint=models.UniqueConstraint(fields=('book', 'rule'), name='unique_rule'),
        ),
        migrations.AddConstraint(
            model_name='bookpartaker',
            constraint=models.UniqueConstraint(fields=('book', 'user', 'job'), name='unique_book_partaker_job'),
        ),
    ]
