# Generated by Django 2.2.3 on 2019-07-11 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpartaker',
            name='job',
            field=models.CharField(choices=[('WRITER', 'Writer'), ('ILLUSTRATOR', 'Illustrator'), ('DIRECTOR', 'Director')], max_length=15),
        ),
        migrations.AlterField(
            model_name='bookrule',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterpartaker',
            name='job',
            field=models.CharField(choices=[('WRITER', 'Writer'), ('ILLUSTRATOR', 'Illustrator')], max_length=15),
        ),
    ]
